### ISSUE TITLE
Include settings in PBXBuildFile

### ISSUE THREAD

**Issue by pepibumur** [xcodeswift/xcproj#137]
## Context 🕵️‍♀️
I opened a project with `xcproj` and after saving it most of the `PBXBuildFile`s didn't match with the ones before.

## What 🌱
It turned out that the `settings` property needs to be written, even if the dictionary is empty:

```plist
// After
04EDB82C1F3B4A5C00411A92 /* AlertStoryboards.m in Sources */ = {isa = PBXBuildFile; fileRef = 04EDB7FA1F3B4A5C00411A92 /* AlertStoryboards.m */; };

// Before
04EDB82C1F3B4A5C00411A92 /* AlertStoryboards.m in Sources */ = {isa = PBXBuildFile; fileRef = 04EDB7FA1F3B4A5C00411A92 /* AlertStoryboards.m */; settings = {}; };
```

## Proposal 🎉
Update `PBXBuildFile` to include the settings dictionary as well.

**Comment by allu22** [comment]
@pepibumur are you sure you got the problem the correct way? I currently have a problem where `settings = {};` gets added when Xcode does not add it. And it seems the bug is here:
https://github.com/xcodeswift/xcproj/blob/780282e21cd265245d0dc35033e40ac35fb0ffb2/Sources/xcproj/PBXBuildFile.swift#L41
It always falls back to empty dictionary.

**Comment by pepibumur** [comment]
You are right, I interpreted it the other way around. We should update the line that you mention to keep the dictionary as nil if there's no `settings` in the read dictionary.
