### ISSUE TITLE
Minimum Deployment target

### ISSUE THREAD

**Issue by olbrichj** [xcodeswift/xcproj#228]
## Context 🕵️‍♀️  
Apps and frameworks have a minimum deployment target, which defines the lowest OS version, on which they can run.

## What 🌱  
Currently the Carthage.xcodeproj defines the following minimum deployment targets:  
iOS: 11.2  
mac: 10.13  
This forces the very current OS versions. Is this necessary? A lot of users (especially on macOS) are on older versions and this would force developers to only support the above versions upwards.

## Proposal 🎉
I've got it running on at least macOS 10.12. So the current requirement is not necessary. I would suggest lowering the deployment target to the lowest version you want to support. If you provide me with the info I can create a PR.

**Comment by yonaskolb** [comment]
Good point @olbrichj.
The carthage project is generated via [Xcodegen](https://github.com/yonaskolb/XcodeGen). To change the deployment target the [carthage-project.yml](https://github.com/xcodeswift/xcproj/blob/master/carthage-project.yml) needs to define them explicitly otherwise it uses the default of the newest SDK's in Xcode
```yaml
name: Carthage
options:
  deploymentTarget:
    iOS: 9.0
    macOS: 10.11
...
```
and the project has to be regenerated with `rake generate_carthage_project`

Not sure what sensible values are here. I don't have an older version of macOS to test with. To be sure we could try some different versions on travis. I think the above values should be fine though.

@olbrichj are you happy to open a PR for this?

**Comment by olbrichj** [comment]
Found the time today :D. Though XcodeGen parses 10.10 oddly. It results in 10.1 so, for now, it's set to 10.11. Will create an issue in XcodeGen correspondingly.  
On the other hand I've tried your suggested version via `options` but it didn't work. So the PR uses IPHONEOS_DEPLOYMENT_TARGET and MACOSX_DEPLOYMENT_TARGET.
