### ISSUE TITLE
Support Carthage

### ISSUE THREAD

**Issue by olbrichj** [xcodeswift/xcproj#41]
## Context
Some developers might build a macOS app that leverages xcodeproj. To make the integration easy, you could support Carthage from xcodeproj. Compared to CocoaPods Carthage provides more control for developers and less version screw ups.

## What
Support Carthage (dynamic framework necessary)

## Proposal
Create xcodeproj as a framework to support Carthage

**Comment by yonaskolb** [comment]
This would require Carthage adding support for Swift PM packages. There's an open PR for that https://github.com/Carthage/Carthage/pull/1945

The other option is to check in a custom xcode project. I'm not sure that carthage is compatible with the one that Swift PM generates (hence the trouble in the above PR), otherwise we'd have to do it ourselves. Maybe we can dog-food https://github.com/yonaskolb/XcodeGen and use that to generate the project

**Comment by pepibumur** [comment]
Would we build a circular dependency if we use XcodeGen? :trollface: @yonaskolb.

**Comment by pepibumur** [comment]
I don't think we can reuse the project that gets generated by SPM. I think we should automate the process of generating that project, and XcodeGen is the best candidate to do that.

**Comment by pepibumur** [comment]
We'll work on this @olbrichj, great idea 😛

**Comment by pepibumur** [comment]
We'll work on this for the next version, 0.1.3

**Comment by olbrichj** [comment]
sounds great 👍

**Comment by toshi0383** [comment]
I think generating Carthage compatible xcodeproj is too much for this core library.
Shouldn't this feature be outside of `xcproj`?
I think `xcproj` should focus on providing API to access xcodeproj related files.

**Comment by pepibumur** [comment]
I guess it was proposed because we also support CocoaPods. I was thinking about two options:
- Either not gitignoring the SPM project and see if Carthage can use that to generate the framework.
- Use XcodeGen to automate the creation of the Carthage project and generate it as part of the release process.

What do you think @toshi0383 ?

**Comment by toshi0383** [comment]
Oh I understood.
I think second option is better and safer. SPM generated one can lose Carthage compatibility in future, even if it was compatible now.

**Comment by toshi0383** [comment]
> Either not gitignoring the SPM project and see if Carthage can use that to generate the framework.

I confirmed in version `Swift 4.0.0-dev (swiftpm-13126)` and it is not Carthage compatible.
It's even missing Info.plist.
```
executable $ tree
.
├── Package.swift
├── README.md
├── Sources
│   └── executable
│       └── main.swift
├── Tests
└── executable.xcodeproj
    ├── project.pbxproj
    ├── project.xcworkspace
    │   ├── contents.xcworkspacedata
    │   └── xcuserdata
    │       └── a14786.xcuserdatad
    │           └── UserInterfaceState.xcuserstate
    ├── xcshareddata
    │   └── xcschemes
    │       ├── executable-Package.xcscheme
    │       └── xcschememanagement.plist
    └── xcuserdata
        └── a14786.xcuserdatad
            └── xcschemes
                └── xcschememanagement.plist
```

**Comment by toshi0383** [comment]
Oops, sorry it was executable type, not library.

**Comment by pepibumur** [comment]
Cool! Would you like to tackle this @toshi0383 ?

**Comment by toshi0383** [comment]
Hmm maybe not right now. wish I had time to do this.
